---
- hosts: all
  become: yes
  tasks:
    - name: Pull Docker image
      command: "docker pull teja694/financeapp:latest"

    - name: Run Docker container
      command: "docker run -d -p 8080:8080 financeapp:latest"
