---
- hosts: all
  become: yes
  tasks:
    - name: Docker Login using shell
      docker_login:
        username: {{ username }}
        password:  {{ password }}

    - name: Run container
      docker_container:
        name: "financeapp"
        image: "financeapp"
        state: present
        pull: true
        restart_policy: always
        ports:
          - "8080:8080"

    - name: Log out of DockerHub
      docker_login:
        state: absent