---
- hosts: test_server
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install Java
      apt:
        name: openjdk-17-jdk
        state: present
